insert into CUSTOM_USER(ID,AUTHOR_PSEUDONMY) values(1,'LOHGARRA');
insert into CUSTOM_USER(ID,AUTHOR_PSEUDONMY) values(2,'PINKFLOYD');
insert into CUSTOM_USER(ID,AUTHOR_PSEUDONMY) values(3,'ANGEL');


insert into BOOK(ID,TITLE,DESCRIPTION,AUTHOR_ID,COVER_IMAGE,PRICE) values(1,'ON THE WAY',NULL,1,NULL,10.99);
insert into BOOK(ID,TITLE,DESCRIPTION,AUTHOR_ID,COVER_IMAGE,PRICE) values(2,'SHARD AND THE MOON',NULL,3,NULL,5.25);
insert into BOOK(ID,TITLE,DESCRIPTION,AUTHOR_ID,COVER_IMAGE,PRICE) values(3,'DARKLY CITIES',NULL,2,NULL,2.99);
insert into BOOK(ID,TITLE,DESCRIPTION,AUTHOR_ID,COVER_IMAGE,PRICE) values(4,'HUNGER GAMES',NULL,2,NULL,30.50);
insert into BOOK(ID,TITLE,DESCRIPTION,AUTHOR_ID,COVER_IMAGE,PRICE) values(5,'AMSTERDAM UNDER THE STARS',NULL,1,NULL,19.99);




