CREATE TABLE CUSTOM_USER (
  ID DECIMAL(19,0) IDENTITY primary key,
  AUTHOR_PSEUDONMY VARCHAR(20) NOT NULL
);

CREATE TABLE BOOK (
    ID DECIMAL(19,0) IDENTITY primary key,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(100) NULL,
    AUTHOR_ID DECIMAL(19,0) NOT NULL,
    COVER_IMAGE VARCHAR(50) NULL,
    PRICE DECIMAL(19,2) NOT NULL
)

